name: flow-subgraph-test
on: [push, pull_request]
env:
  NODE_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1
        with:
          version: latest

      - name: Use Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: $NODE_VERSION

      - name: Install dependencies
        run: |
          npm ci

      - name: Build Docker Compose images
        run: |
          docker-compose down
          docker-compose up --build -d

      - name: Run Subgraph tests
        run: |
          npm run test

      - name: Stop containers
        run: docker-compose down
